### ISSUE TITLE
do u have plans to enhance it ?

### ISSUE THREAD

**Issue by harinanda** [ruddell/ignite-jhipster#13]

**Comment by mfalzetta** [comment]
O have the same question.

One thing, support of comunity for react is so easy as Ionic?

Becouse issues with Angar 2 and Cordova and Ionic is easy find in fóruns how stackovefow...

**Comment by ruddell** [comment]
@harinanda You can see my current plans in the other issues, then I'll release the v1 beta.  Did you have certain features in mind for enhancing?

@mfalzetta This boilerplate just adds some JHipster benefits to the basic ignite-boilerplate, like user login, settings, and entity generation.  One of the reasons I decided to integrate with the Ignite generator is their great community support.  I've been able to Google most issues, and for the hard problems there is a Slack channel with react-native and ignite support (http://community.infinite.red/)

**Comment by ruddell** [comment]
Closing due to no response
