### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by ruddell** [ruddell/ignite-jhipster#19]
### Planned Features:
 - [x] Websocket Support
 - [ ] Social Login
 - [x] Internationalization (not much interest, please open an issue if you want it)

### To Investigate
 - [x] React-Navigation

**Comment by caffeinecoders** [comment]
+1 for Social login support. Really looking forward to social login support.

**Comment by justmx** [comment]
+1 for Social login support and React-Navigation please.

**Comment by dishaverma1987** [comment]
+1 for social login support

**Comment by rakeshkalra1983** [comment]
++1 really waiting for social login support

**Comment by JatinDesai** [comment]
This is really a fantastic boilerplate. It will be really great if this includes offline app support with Redux-Offline library or something similar.

**Comment by ruddell** [comment]
Websockets are done and in beta release, which means Social Login is up next (and I can tell a lot of people want it).  The good news is that I've got it mostly working!  I'll do my best to add this to the generator before the end of the year.  For now, I added [some docs](https://github.com/ruddell/ignite-jhipster/blob/master/docs/social-login.md) detailing how it can be configured.

In regards to `react-navigation`, I recently upgraded `react-native-router-flux` to v4 which is based on `react-navigation`'s API (and actually uses `react-navigation` for some things like the Drawer support).  I'm going to keeps the library the same for now, but the configuration is very similar to `react-navigation` if you wish to change.

@JatinDesai I'm hoping someone will write an Ignite plugin for redux-offline.  It isn't something specific to JHipster backends which is something I'm catering to with this boilerplate.

**Comment by rakeshkalra1983** [comment]
Thanks a lot @ruddell I really appreciate your help here regarding social login.

Kindly update if the above technique for social login will work if I have used keycloak integration with Jhipster or Jhipster UAA also? Or if not, I will be really thankful if you can guide how can same be achieved?

**Comment by ruddell** [comment]
@rakeshkalra1983 Keycloak supports social login, but I don't have any experience with it so I would refer to their docs.  UAA doesn't support social login without customizations, this is not currently possible with the main JHipster generator.

While my goal is to support JHipster's social login, you will still be able to manage the social access tokens yourself.

**Comment by rakeshkalra1983** [comment]
Ok, I didn't know that UAA doesn't support social login. 

But still, I really appreciate your help and work here. This is really useful :) 
Many thanks to you.

**Comment by ruddell** [comment]
[GIF showing Facebook Auth](https://user-images.githubusercontent.com/4294623/34912871-63555a46-f8ba-11e7-846e-b36c98871579.gif)

I can confirm social login works on iOS nicely.  I'm waiting to do a release until I find time to test it on Android.  Full configuration instructions can be found [in the docs](https://github.com/ruddell/ignite-jhipster/blob/master/docs/social-login.md)
