### ISSUE TITLE
React Native Mobile App with out Server

### ISSUE THREAD

**Issue by Ramaraju1992** [ruddell/ignite-jhipster#202]
Hi,

When I try to create a React Native Mobile Application using `ignite new HealthPoints -b ignite-jhipster` 
command line, it promotes me asking for `? Enter the path to your JHipster project root directory: (backend)`.

But I wanted to create a **React Native Mobile Application** with out Server.

I found `jhipster --skip-server` will work, but for **Web Applications**. 

is there any similar way to create a **React Native Mobile Application** with out Server.

**Comment by ruddell** [comment]
This generator only creates the JHipster React Native client, it does not generate a server.  It expects you to have a server already.

You can use JDL to get around that prompt, but you'll have an app with screens expecting to communicate with a JHipster backend (login, settings, register, and more).  For example:
```
# create a blank JDL with default options
echo "application {}" >> 21-points.jh

# or use the real HealthPoints JDL file
wget https://raw.githubusercontent.com/jhipster/jdl-samples/main/21-points.jh

# generate the app
npx ignite-cli@3 new HealthPoints -b ignite-jhipster --jdl 21-points.jh
```
