### ISSUE TITLE
Error loading boilerplate

### ISSUE THREAD

**Issue by slayer49** [ruddell/ignite-jhipster#21]
Getting this error when trying to create a new ignite app from the boilerplate.   This worked previously for me.

`$ ignite new MySdMobile --boilerplate ignite-jhipster
Directory MySdMobile already exists.
? Do you want to overwrite this directory? true
Overwriting MySdMobile...
-----------------------------------------------
  (                  )   (                   
  )\ )   (        ( /(   )\ )    *   )       
 (()/(   )\ )     )\()) (()/(  ` )  /(   (   
  /(_)) (()/(    ((_)\   /(_))  ( )(_))  )\  
 (_))    /(_))_   _((_) (_))   (_(_())  ((_) 
 |_ _|  (_)) __| | \| | |_ _|  |_   _|  | __|
  | |     | (_ | | .` |  | |     | |    | _| 
 |___|     \___| |_|\_| |___|    |_|    |___|
-----------------------------------------------

An unfair headstart for your React Native apps.
https://infinite.red/ignite

-----------------------------------------------

🔥 igniting app MySdMobile
✖ error loading the boilerplate`

**Comment by ruddell** [comment]
Thanks for testing!  I just fixed this in https://github.com/ruddell/ignite-jhipster/commit/f9b1688019ad50aafe0dd0ecb2c9b332f7ee5e9d and added a new release.  It should work now.
