### ISSUE TITLE
UAA integration example

### ISSUE THREAD

**Issue by delkant** [ruddell/ignite-jhipster#26]
Hi,

Thank you for sharing this great project!

I am having problems generating a microservices architecture project with Jhipster-UAA(which I assume will work with the uaa option in ingite-jhipster).

I have a Jhipster registry, uaa, gateway and a "one entity-field" microservice app. But I couldn't figure out how to configure this on the Config/AppConfig.js file.

I can see the authentication in the backend is happening but my app is not moving from the login screen.

Not sure if there is another config file I need to modify or the problem is because I am pointing to the gateway instead of going directly to the uaa service. Any advice will be welcome, I am new in react so I am still trying to learn how everything was built.

Thanks again!

**Comment by ruddell** [comment]
Hi @delkant, you are correct that all requests should go through the gateway.  The only thing you need to make sure of in `Config/AppConfig.js` is that your `apiUrl` is correct and the `uaaBaseUrl` matches what you chose when generating your UAA.

Can you please tell me what versions you used for the following:
 - generator-jhipster (look in `.yo-rc.json` of your UAA and Gateway)
 - ignite-jhipster (look in your `package.json` of your IgniteJhipster app

I just tried running a sample app using UAA and I didn't see any issues so hopefully we can trace down what happened here.

**Comment by delkant** [comment]
Thanks for the quick reply.

gateway `.yo-rc.json`

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gw.admin",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.13.0",
    "baseName": "gateway",
    "packageName": "com.gw.admin",
    "packageFolder": "com/gw/admin",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "AAuth",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "couchbase",
    "devDatabaseType": "couchbase",
    "prodDatabaseType": "couchbase",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

ignite `package.json`

{
  "name": "TheApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean --force",
    "clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
    "newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean --force && npm i",
    "test:watch": "jest --watch",
    "updateSnapshot": "jest --updateSnapshot",
    "coverage": "jest --coverage && open coverage/lcov-report/index.html || xdg-open coverage/lcov-report/index.html",
    "android:build": "cd android && ./gradlew assembleRelease",
    "android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
    "android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
    "android:devices": "$ANDROID_HOME/platform-tools/adb devices",
    "android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
    "android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
    "precommit": "npm run git-hook",
    "prepush": "npm run git-hook",
    "git-hook": "npm run lint -s && npm run test -s",
    "storybook": "storybook start -p 7007",
    "lint": "standard --verbose | snazzy",
    "lintdiff": "git diff --name-only --cached --relative | grep '\\.js$' | xargs standard | snazzy",
    "fixcode": "standard --fix"
  },
  "dependencies": {
    "apisauce": "0.14.2",
    "format-json": "1.0.3",
    "identity-obj-proxy": "3.0.0",
    "lodash": "4.17.4",
    "prop-types": "15.6.0",
    "querystringify": "1.0.0",
    "ramda": "0.25.0",
    "react": "16.0.0",
    "react-native": "0.50.4",
    "react-native-config": "0.10.0",
    "react-native-cookies": "3.2.0",
    "react-native-keyboard-aware-scroll-view": "0.4.1",
    "react-native-router-flux": "4.0.0-beta.24",
    "react-native-vector-icons": "4.3.0",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-persist": "5.4.0",
    "redux-saga": "0.16.0",
    "reduxsauce": "0.7.0",
    "seamless-immutable": "7.1.2",
    "tcomb-form-native": "0.6.11"
  },
"devDependencies": {
    "@storybook/addon-storyshots": "3.2.16",
    "@storybook/addons": "3.2.16",
    "@storybook/channels": "3.2.16",
    "@storybook/react-native": "3.2.16",
    "babel-core": "6.26.0",
    "babel-eslint": "7.1.1",
    "babel-jest": "22.0.4",
    "babel-plugin-ignite-ignore-reactotron": "0.3.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-react-native": "3.0.2",
    "buffer": "5.0.8",
    "enzyme": "3.2.0",
    "enzyme-adapter-react-16": "1.1.0",
    "ignite-ir-boilerplate": "^2.3.1",
    "ignite-jhipster": "^1.5.1",
    "ignite-standard": "^1.0.0",
    "ignite-vector-icons": "^1.1.0",
    "jest": "21.2.1",
    "mockery": "2.1.0",
    "react-dom": "16.0.0",
    "react-test-renderer": "16.0.0",
    "reactotron-react-native": "1.13.2",
    "reactotron-redux": "1.13.0",
    "reactotron-redux-saga": "1.13.0",
    "snazzy": "^7.0.0",
    "standard": "10.0.2"
  },
  "jest": {
    "testMatch": [
      "**/Tests/**/*.js",
      "**/?(*.)(spec|test).js?(x)"
    ],
    "testPathIgnorePatterns": [
      "/node_modules/",
      "Tests/Setup.js"
    ],
    "moduleNameMapper": {
      "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "identity-obj-proxy"
    },
    "setupFiles": [
      "./Tests/Setup"
    ],
    "coveragePathIgnorePatterns": [
      "App/Services/Api.js",
      "App/Themes/",
      "/storybook/",
      "/*\\.story\\.js"
    ],
    "preset": "react-native"
  },
"config": {},
  "standard": {
    "parser": "babel-eslint",
    "globals": [
      "describe",
      "test",
      "jest",
      "expect",
      "fetch",
      "navigator",
      "__DEV__",
      "XMLHttpRequest",
      "FormData",
      "React$Element"
    ],
    "ignore": [
      "ignite/**"
    ]
  }
}

**Comment by ruddell** [comment]
What did you set the value of `uaaBaseUrl` to in AppConfig.js?  In your case, it should be `aauth/`

I added a comment to clarify that variable and also fixed the UAA logout URL (something you'll need to do yourself if you continue with the existing project). See https://github.com/ruddell/ignite-jhipster/commit/f157e754abcb0ced525e85f5baa1301d455f285f

**Comment by delkant** [comment]
Sorry my bad! 

The `uaaBaseUrl` was my problem, i found the right url when I went to the browser and my app here http://localhost:8080/#/gateway (where the current routes are listed)

My problem now is that the **Logout** is not working in the Ignite App.

**Comment by delkant** [comment]
Just saw your comment on the Logout URL! Thanks!

**Comment by ruddell** [comment]
For the logout, see the change here: https://github.com/ruddell/ignite-jhipster/commit/f157e754abcb0ced525e85f5baa1301d455f285f#diff-352787f231b1774d296c3bd38b72fa99
