### ISSUE TITLE
Fields mark as 'required' are shown as 'optional' when creating/editing a entity

### ISSUE THREAD

**Issue by delkant** [ruddell/ignite-jhipster#27]
This is the .jhipster/entity.json
```

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "barcode",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "metadata",
            "fieldType": "String"
        },
        {
            "fieldName": "statusId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "createdAt",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "createdBy",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20180111125645",
    "entityTableName": "entity",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "jpaMetamodelFiltering": false,
    "microserviceName": "ATracker"
}
```

![entityjson](https://user-images.githubusercontent.com/1325846/34831947-7e8d6458-f6b6-11e7-8c8b-109a43f1a86f.png)

**Comment by delkant** [comment]
If you point me to the place where I can help with this I can try to create a PR so I can collaborate in the future.

**Comment by ruddell** [comment]
The place to fix this would be https://github.com/ruddell/ignite-jhipster/blob/master/templates/entity-edit-screen.ejs#L20-L39

The form is built with [tcomb-form-native](https://github.com/gcanti/tcomb-form-native) which uses `t.maybe(fieldname)` to make a field optional.  If required, it should just be `fieldname`.  I'll have some time this weekend to look into it if you don't get to it, thanks again for your feedback

**Comment by ruddell** [comment]
I went ahead and refactored that entire section to make the purpose clear, fixed this in the process

**Comment by delkant** [comment]
👍  Amazing! Thank you! I got stuck with my job couldn't start working on the fix, you're the best! Will do my best to collaborate to this project as soon as I get more time free. I think it is an amazing project and a great fit for Jhipster's environment.
