### ISSUE TITLE
Ignite JHipster needs OAuth support to be refactored

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#30]
With the rewrite of JHipster's OAuth support to use an external IdP, the OAuth support in this library no longer works. You should be able to use OAuth's implicit flow to get an access token from the IdP and make API calls with it in the `Authorization` header. 

This is what I did with the Ionic Module for JHipster and it works well. I also added an [`AuthInfoResource`](https://github.com/oktadeveloper/generator-jhipster-ionic/blob/master/generators/app/templates/src/main/java/package/web/rest/AuthInfoResource.java) that we might want to add automatically when users choose OAuth in JHipster.

**Comment by ruddell** [comment]
I got this mostly implemented in de7bf591a80335b9eba7c04cfced63070bad3dc6 and finished up in a few later commits.  It works well, thanks for setting up the backend part.

**Comment by mraible** [comment]
FWIW, I was able to get https://github.com/FormidableLabs/react-native-app-auth working this week. Its [example](https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example) only requires you to change a [few properties](https://github.com/FormidableLabs/react-native-app-auth/blob/master/Example/App.js#L22) to switch providers. These are the same properties that come from the `/api/auth-info` endpoint.

**Comment by ruddell** [comment]
I looked at a few of the libraries out there but most of them require you to install a separate native library in iOS and in Android then keep those up to date separately (on top of their npm module).  For more advanced apps that enable refresh tokens and other Oauth2 features it would be useful, but as long as I'm the only maintainer here, I plan to keep it simple and functional.
