### ISSUE TITLE
Consume rest api via IP endpoint ok, but via DOMAIN endpoint alway return 0 all real android device

### ISSUE THREAD

**Issue by xuuz** [ruddell/ignite-jhipster#37]
Dear @ruddell 
For iOS every thing work very nice both device and simulator, but with real Android device and simulator just can config with IP rest endpoint, every thing work well.

But when I change to domain, HTTP status alway return 0 both device and simulator
Could you please help me in this case?

Thanks a million.

**Comment by ruddell** [comment]
The IgniteJHipsterSampleApp in the Android app store uses a domain for the API url so I have no clue sorry https://github.com/ruddell/IgniteJhipsterSampleApp/blob/master/App/Config/AppConfig.js#L4

Do you have a `/` at the end of your domain?

**Comment by ruddell** [comment]
I see HTTP Status 0 when the API is unreachable but a regular response when the API is reachable from the device.

![screen shot 2018-03-14 at 10 13 47 am](https://user-images.githubusercontent.com/4294623/37407598-7019da38-2770-11e8-8f3f-179095d2a65d.png)
![screen shot 2018-03-14 at 10 13 36 am](https://user-images.githubusercontent.com/4294623/37407599-704b4910-2770-11e8-8c16-3c627188f928.png)

**Comment by xuuz** [comment]
Thanks for your answer @ruddell , 
It's worked perfect right now

Thanks a million.
