### ISSUE TITLE
Submit/Save form 

### ISSUE THREAD

**Issue by breechiteri** [ruddell/ignite-jhipster#39]
I would like to save my form to the jHipster backend but i get an error 
![image](https://user-images.githubusercontent.com/31438922/38298510-361f2efa-3800-11e8-8251-fcfa60785a48.png)

this is my code:
```
import React from 'react'
import { Alert, ScrollView, Text, TouchableHighlight, DatePickerAndroid } from 'react-native'
import { connect } from 'react-redux'
import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'
// Add Actions - replace 'Your' with whatever your reducer is called :)
//  import AccountActions from '../Redux/AssessmentRedux'
import { Actions as NavigationActions } from 'react-native-router-flux'
import RoundedButton from '../Components/RoundedButton' // eslint-disable-line
import AssessmentActions from '../Redux/AssessmentRedux'
import t from 'tcomb-form-native'
// Styles
import styles from './Styles/NewAssessmentScreenStyle'
import moment from 'moment'
let Form = t.form.Form

class NewAssessmentScreen extends React.Component {
  constructor (props) {
    super(props)
    this.state = { 
        accountModel: t.struct({
        enumerator: t.String,
        participant: t.String,
        interviewee: t.String,
        assessmentType: t.String,
        factory: t.form.Radio
      //  startDate: t.Date 
        
        
      }),
      accountValue: this.props.account,
      options: {
        fields: {
          enumerator: {
            returnKeyType: 'next',
            onSubmitEditing: () => this.refs.form.getComponent('participant').refs.input.focus()
          },
          participant: {
            returnKeyType: 'next',
            onSubmitEditing: () => this.refs.form.getComponent('interviewee').refs.input.focus()
          },
          interviewee: {
            returnKeyType: 'next',
            onSubmitEditing: () => this.refs.form.getComponent(' assessmentType').refs.input.focus()
          },
          assessmentType: {
            returnKeyType: 'done',
            onSubmitEditing: () => this.refs.form.getComponent(' startDate').refs.input.focus()
          }, 
                       
        }
      },
      success: false
    }
    this.submitUpdate = this.submitUpdate.bind(this)
    this.accountChange = this.accountChange.bind(this)
  }

   submitUpdate () {
    this.setState({
      success: false
    })
    // call getValue() to get the values of the form
    const value = this.refs.form.getValue()
    if (value) { // if validation fails, value will be null
      this.props.assessmentUpdateRequest (value)
    }
  }

  componentWillReceiveProps (newProps) {
    // Did the update attempt complete?
    if (!newProps.updating) {
      if (newProps.error) {
        if (newProps.error === 'WRONG') {
          Alert.alert('Error', 'Something went wrong while saving the settings', [{text: 'OK'}])
        }
      } else if (!this.state.success) {
        this.setState({
          success: true
        })
        Alert.alert('Success', 'Assessments updated', [{text: 'OK'}])
        this.props.getAccount()
      }
    }
  }

  accountChange (newValue) {
    this.setState({
      accountValue: newValue
    })
  }

  render () {
    var Person = t.struct({
      effectiveDate: t.Date // a date field
  });
  let myFormatFunction = (format,date) =>{
      return moment(date).format(format);
  }
  var effectiveDate = {
      label: 'Effective Date',
      mode:'date',
      config:{
          format:(date) => myFormatFunction("DD MMM YYYY",date)
      }
  };
  let options = {
      fields: {
         "effectiveDate":effectiveDate
      }
  };


    return (
      <KeyboardAwareScrollView>
        <ScrollView style={styles.container}>
          <Form
            ref='form'
            type={this.state.accountModel}
            options={this.state.options}
            value={this.state.accountValue}
            onChange={this.accountChange}
            
          />
           <Form ref="documentDate" type={Person} value={this.state.dateValue} options={options} />
          <TouchableHighlight style={styles.button} onPress={this.submitUpdate} underlayColor='#99d9f4'>
            <Text style={styles.buttonText}>Save</Text>
          </TouchableHighlight>

           
         <RoundedButton text='Start Child Assessment' onPress={NavigationActions.startAssessment} />      
         <RoundedButton text='Start Adult Assessment' onPress={NavigationActions.start1Assessment} />  
          


        </ScrollView>
      </KeyboardAwareScrollView>
    )
  }
}

const mapStateToProps = (state) => {
  return {
   account: state.account.account,
    updating: state.account.updating,
    error: state.account.error
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    getAllAssessments: (assessment) => dispatch(AssessmentActions.assessmentUpdateRequest(assessment))
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(NewAssessmentScreen)

```

**Comment by ruddell** [comment]
Could you please supply your JHipster app's `.yo-rc.json` and the entity json file for the entity causing issues (found in `.jhipster/`)? Thanks

**Comment by ruddell** [comment]
Based on the code, it looks like when you call `submitUpdate`, it calls `      this.props.assessmentUpdateRequest (value)` but that is not declared in the props at the bottom.  Your method is named `getAllAssessments` for some reason, maybe a copy/paste issue.

**Comment by breechiteri** [comment]
Thank that is what was casing the error message. After calling
this.props.getAllAssessments but still it does not update the backend

**Comment by ruddell** [comment]
I can't help without any info :)  If it doesn't update the backend then there is an error somewhere

**Comment by breechiteri** [comment]
Ok so i have a back end entity called Assessments. it has the following
fields :
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "many-to-one",
      "relationshipName": "gender",
      "otherEntityName": "gender",
      "otherEntityField": "name"
    },
    {
      "relationshipType": "many-to-one",
      "relationshipName": "state",
      "otherEntityName": "state",
      "otherEntityField": "name"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipValidateRules": "required",
      "relationshipName": "meal",
      "otherEntityName": "meal",
      "otherEntityRelationshipName": "assessment"
    },
    {
      "relationshipType": "many-to-one",
      "relationshipName": "enumerator",
      "otherEntityName": "enumerator",
      "otherEntityField": "code"
    },
    {
      "relationshipType": "many-to-one",
      "relationshipName": "participant",
      "otherEntityName": "participant",
      "otherEntityField": "code"
    },
    {
      "relationshipType": "many-to-one",
      "relationshipName": "interviewerType",
      "otherEntityName": "interviewerType",
      "otherEntityField": "name"
    }
  ],
  "fields": [
    {
      "fieldName": "startDate",
      "fieldType": "ZonedDateTime"
    },
    {
      "fieldName": "child",
      "fieldType": "Boolean"
    }
  ],
  "changelogDate": "20171212075952",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "entityTableName": "assessment"
}

i want my front end app (react-native) to be able to save data to the
entity called Assessments: below is the code for the front end application

import React from 'react'
import { Alert, ScrollView, Text, TouchableHighlight, DatePickerAndroid }
from 'react-native'
import { connect } from 'react-redux'
import { KeyboardAwareScrollView } from
'react-native-keyboard-aware-scroll-view'
// Add Actions - replace 'Your' with whatever your reducer is called :)
// import AccountActions from '../Redux/AssessmentRedux'
import { Actions as NavigationActions } from 'react-native-router-flux'
import RoundedButton from '../Components/RoundedButton' //
eslint-disable-line
import AssessmentActions from '../Redux/AssessmentRedux'

import t from 'tcomb-form-native'
// Styles
import styles from './Styles/NewAssessmentScreenStyle'
import moment from 'moment'
let Form = t.form.Form

class NewAssessmentScreen extends React.Component {
constructor (props) {
super(props)
this.state = {
formModel: t.struct({
enumerator: t.String,
participant: t.String,
interviewee: t.String,
assessmentType: t.String,
// startDate: t.Date
}),
formValue: this.props.form,
options: {
fields: {
enumerator: {
returnKeyType: 'next',
onSubmitEditing: () => this.refs.form.getComponent('participant').refs.input
.focus()
},
participant: {
returnKeyType: 'next',
onSubmitEditing: () => this.refs.form.getComponent('interviewee').refs.input
.focus()
},
interviewee: {
returnKeyType: 'next',
onSubmitEditing: () => this.refs.form.getComponent(' assessmentType').refs.
input.focus()
},
assessmentType: {
returnKeyType: 'done',
onSubmitEditing: () => this.refs.form.getComponent(' startDate').refs.input.
focus()
},
}
},
success: false
}
this.submitUpdate = this.submitUpdate.bind(this)
this.accountChange = this.accountChange.bind(this)
}

submitUpdate () {
this.setState({
success: false
})
// call getValue() to get the values of the form
const value = this.refs.form.getValue()
if (value) { // if validation fails, value will be null
this.props.assessmentUpdateRequest(value)
}
}

componentWillReceiveProps (newProps) {
// Did the update attempt complete?
if (!newProps.updating) {
if (newProps.error) {
if (newProps.error === 'WRONG') {
Alert.alert('Error', 'Something went wrong while saving the settings', [{
text: 'OK'}])
}
} else if (!this.state.success) {
this.setState({
success: true
})
Alert.alert('Success', 'Assessments updated', [{text: 'OK'}])
this.props.assessmentUpdateRequest()
}
}
}

formChange (newValue) {
this.setState({
formValue: newValue
})
}

render () {
var Person = t.struct({
effectiveDate: t.Date // a date field
});
let myFormatFunction = (format,date) =>{
return moment(date).format(format);
}
var effectiveDate = {
label: 'Effective Date',
mode:'date',
config:{
format:(date) => myFormatFunction("DD MMM YYYY",date)
}
};
let options = {
fields: {
"effectiveDate":effectiveDate
}
};


return (
<KeyboardAwareScrollView>
<ScrollView style={styles.container}>
<Form
ref='form'
type={this.state.accountModel}
options={this.state.options}
value={this.state.accountValue}
onChange={this.accountChange}
/>
<Form ref="documentDate" type={Person} value={this.state.dateValue} options=
{options} />
<TouchableHighlight style={styles.button} onPress={this.submitUpdate}
underlayColor='#99d9f4'>
<Text style={styles.buttonText}>Save</Text>
</TouchableHighlight>

<RoundedButton text='Start Child Assessment' onPress={NavigationActions.
startAssessment} />
<RoundedButton text='Start Adult Assessment' onPress={NavigationActions.
start1Assessment} />


</ScrollView>
</KeyboardAwareScrollView>
)
}
}

const mapStateToProps = (state) => {
return {
account: state.account.account,
updating: state.account.updating,
error: state.account.error
}
}

const mapDispatchToProps = (dispatch) => {
return {
assessmentUpdateRequest: (assessment) => dispatch(AssessmentActions.
assessmentUpdateRequest(assessment))
}
}

export default connect(mapStateToProps, mapDispatchToProps)(
NewAssessmentScreen)

**Comment by ruddell** [comment]
Does your backend show any errors on save?

**Comment by ruddell** [comment]
Based on that error, it looks like you aren't correctly formatting the object to be saved.  I recommend examining the requests on the regular JHipster frontend and comparing to your requests to see how you should format the data.  

You need to include the enumerator ID, so the full request should look like:

    {"startDate":"2192-09-03T01:09:00.000Z","child":true,"enumerator":{"id":1,"code":"test","assessments":null}}

I get the same error as you when the request looks like:

    {"startDate":"2192-09-03T01:09:00.000Z","child":true,"enumerator":"test"}
