### ISSUE TITLE
Fetch data from different jHipster entities and display on pickers 

### ISSUE THREAD

**Issue by breechiteri** [ruddell/ignite-jhipster#41]
I need help here: I have two pickers and a flat-list on one screen i would like to fetch data from two entities on my back-end and be able to display the different data fetch on the two pickers and flat list.

Unfortunately they are all displaying data from the last entered entity am using component will receive props 

I believe the problem is with this function how can i ensure that each picker fetches the data from the right entity ?

componentWillReceiveProps (newProps) {
  if (newProps.mealTypes) {
    this.setState({
      done: newProps.mealTypes.length < this.state.size,
      dataObjects: this.state.loading ? [...this.state.dataObjects, ...newProps.mealTypes] : newProps.mealTypes,
      loading: false
    })
  };
  if (newProps.mealPreparationPlaces) {
    this.setState({
      done: newProps.mealPreparationPlaces.length < this.state.size,
      dataObjects: this.state.loading ? [...this.state.dataObjects, ...newProps.mealPreparationPlaces] : newProps.mealPreparationPlaces,
      loading: false
    })
  }
}

**Comment by ruddell** [comment]
Can you describe the issue a little more?  Are you querying for both entities?  Looking at your code it seems you are storing both entities in the `state.dataObjects` variable.  Is that what you want?

**Comment by breechiteri** [comment]
**This is the full code:**

import React, { Component } from 'react'
import { ScrollView, AppRegistry,
    Text,
  View,
   Alert, Picker, KeyboardAvoidingView } from 'react-native'


import { connect } from 'react-redux'
// Add Actions - replace 'Your' with whatever your reducer is called :)
// import YourActions from '../Redux/YourRedux'

// Styles
//import styles from './Styles/FoodIngredientsScreenStyle'
import MealPreparationPlaceActions from '../Redux/MealPreparationPlaceRedux'
import MealTypeActions from '../Redux/MealTypeRedux'
import { Actions as NavigationActions } from 'react-native-router-flux' // eslint-disable-line

// For empty lists
import AlertMessage from '../Components/AlertMessage'

class FoodIngredientsScreen extends Component {
  state = {
    page: 0,
    sort: 'id,asc',
    size: 20,
    loading: true,
    done: false,
    dataObjects: []
  }
 

  renderRow ({item}) {
    return (
      <TouchableOpacity onPress={NavigationActions.mealTypeEntityDetail.bind(this, { entityId: item.id })}>
        <View style={styles.row}>
          <Text style={styles.boldLabel}>{item.id}</Text>
          {/* <Text style={styles.label}>{item.description}</Text> */}
        </View>
      </TouchableOpacity>
    )
  }

  renderEmpty = () =>
  <AlertMessage title='No MealTypes Found' show={!this.props.fetching} />

// renderSeparator = () =>
//  <Text style={styles.label}> - ~~~~~ - </Text>

// The default function if no Key is provided is index
// an identifiable key is important if you plan on
// item reordering.  Otherwise index is fine
keyExtractor = (item, index) => index

// How many items should be kept in memory as we scroll?
oneScreensWorth = 20

fetchMealTypes = () => {
  this.props.getAllMealTypes({ page: this.state.page, sort: this.state.sort, size: this.state.size })
};

fetchMealPreparationPlaces = () => {
  this.props.getAllMealPreparationPlaces({ page: this.state.page, sort: this.state.sort, size: this.state.size })
}

handleLoadMore = () => {
  if (this.state.done || this.props.fetching) {
    return
  }
  this.setState({
    page: this.state.page + 1,
    loading: true
  })
  this.fetchMealTypes();
  this.fetchMealPreparationPlaces()
}

componentWillReceiveProps (newProps) {
  if (newProps.mealTypes) {
    this.setState({
      done: newProps.mealTypes.length < this.state.size,
      dataObjects: this.state.loading ? [...this.state.dataObjects, ...newProps.mealTypes] : newProps.mealTypes,
      loading: false
    })
  }
}
  componentWillReceiveProps (newProps) {
  if (newProps.mealPreparationPlaces) {
    this.setState({
      done: newProps.mealPreparationPlaces.length < this.state.size,
      dataObjects: this.state.loading ? [...this.state.dataObjects, ...newProps.mealPreparationPlaces] : newProps.mealPreparationPlaces,
      loading: false
    })
  }
}


componentWillMount () {
  
 this.fetchMealPreparationPlaces()
 this.fetchMealTypes()
}

  render () {
    return (
      <ScrollView style={styles.container}>

       <Picker style={styles.picker} 
          itemStyle={styles.items}
          selectedValue={this.state.name}
          onValueChange={(name) => this.setState({name:name})}>
          {this.state.dataObjects.map((mealType, key) => (
             <Picker.Item label={"Meal Type: " + mealType.name} value={mealType.name} key={key} 
            /> )
          )}
     </Picker>

     <Picker style={styles.picker} 
          itemStyle={styles.items}
          selectedValue={this.state.name}
          onValueChange={(name) => this.setState({name:name})}>
          {this.state.dataObjects.map((mealPreparationPlace, key) => (
             <Picker.Item label={"Meal Preparation: " + mealPreparationPlace.name} value={mealPreparationPlace.name} key={key} 
            /> )
          )}
     </Picker>

      </ScrollView>
    )
  }
}

const mapStateToProps = (state) => {
  return {
    // ...redux state to props here
   
    mealTypes: state.mealTypes.mealTypes,
    fetching: state.mealTypes.fetchingAll,
    error: state.mealTypes.errorAll,
    mealPreparationPlaces: state.mealPreparationPlaces.mealPreparationPlaces,
    fetching: state.mealPreparationPlaces.fetchingAll,
    error: state.mealPreparationPlaces.errorAll
  }
}

const mapDispatchToProps = (dispatch) => {
  return {

    getAllMealTypes: (options) => dispatch(MealTypeActions.mealTypeAllRequest(options)),
    getAllMealPreparationPlaces: (options) => dispatch(MealPreparationPlaceActions.mealPreparationPlaceAllRequest(options))
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(FoodIngredientsScreen)

**Comment by ruddell** [comment]
I would recommend:
 - Adding an array for each related entity to the state
   - `mealTypes: []`
   - `mealPreparationPlaces: []`
 - Use those arrays in `componentWillReceiveProps` to store the lists for each entity
   - You currently have two methods named `componentWillReceiveProps`, combine those
 - Use those arrays in the `Picker` instead of `state.dataObjects`

**Comment by breechiteri** [comment]
Thank you very much it is working
