### ISSUE TITLE
How to store JWT token avoid login every time reopen the app

### ISSUE THREAD

**Issue by Chris533** [ruddell/ignite-jhipster#42]
I use AsyncStorage with this , login success at first but then will be failed by Action type: "persist/REHYDRATE".
`setAuthToken: (authToken) => dispatch(LoginActions.loginSuccess(authToken)),`

**Comment by ruddell** [comment]
Where is that code from?  What are the steps to reproduce your issue?  In a newly generated app, the token is loaded fine on app resume

**Comment by Chris533** [comment]
Thanks Ruddell, I find the solution :
Edit _App/Config/ReduxPersist.js_
`    whitelist: ['login', 'account'], // Optionally, just specify the keys you DO want stored to`
