### ISSUE TITLE
Migrate to react-native-navigation

### ISSUE THREAD

**Issue by ruddell** [ruddell/ignite-jhipster#44]
- Migrate from to `react-native-navigation` from `react-native-router-flux`, it doesn't look to be actively developed anymore

**Comment by ruddell** [comment]
See https://github.com/ruddell/ignite-jhipster/pull/48#issuecomment-418185611 for reasoning of staying with current nav library

**Comment by maxto024** [comment]
hey sorry for late but did you get time to migrate to react-navigation from react-native-router-flux if you didn't get time i am happy to do that for

**Comment by ruddell** [comment]
There's an open PR https://github.com/ruddell/ignite-jhipster/pull/54 but it needs some cleaning up.  It's also a breaking change so I'm planning on merging it at the same time as the other PR for a v2 release. 

There's also the issue of https://github.com/ruddell/ignite-jhipster/issues/61 which looks like it requires a React Native upgrade and I'm not sure if react-native-navigation supports v0.57 yet.

Also note I'm talking about https://github.com/wix/react-native-navigation and not https://github.com/react-navigation/react-navigation.

**Comment by maxto024** [comment]
glad to know that since React Native Navigation provides 100% native platform navigation thanks for the awesome boilerplate. So what can I do to accelerate the process of migrating?

**Comment by ruddell** [comment]
I'll try to find time this week to rebase and merge those pull requests.  Help testing will be appreciated once that's complete

**Comment by ruddell** [comment]
I'm merging both PRs into a v2 branch then releasing that in a week or two.  I got react-native-navigation working with v0.57.4 and merged into v2, if you want to try it out in the meantime you can do the following:

```
git clone https://github.com/ruddell/ignite-jhipster.git
cd ignite-jhipster
git checkout v2
ignite new MyApp --boilerplate /full/path/to/cloned/directory
```

**Comment by maxto024** [comment]
Hi @ruddell  woow this is wonderful I have tested and generated v2 app its working great also I notice its faster than before in navigation while this new navigation library is using native 
<img width="423" alt="screen shot 2018-10-29 at 3 55 37 pm" src="https://user-images.githubusercontent.com/17172422/47648433-71292f00-db93-11e8-802c-53631b9e5853.png">

even I generate entity while I was generating entity I get this error 
<img width="915" alt="screen shot 2018-10-29 at 3 56 14 pm" src="https://user-images.githubusercontent.com/17172422/47648466-8c943a00-db93-11e8-9033-bae72cf96e0f.png">

but necessary files of the entity was generated successfully however as you can see entity was not registered to the navigation/layout.js 
<img width="1440" alt="screen shot 2018-10-29 at 4 00 55 pm" src="https://user-images.githubusercontent.com/17172422/47648580-db41d400-db93-11e8-820a-0aa3f060c5be.png">

thanks for the upgrade i look forward the release  as soon as possible

**Comment by ruddell** [comment]
You will also need to run `npm link ignite-jhipster` inside your generated app before generating entities (otherwise it uses the released version instead of your local version).  I forgot to mention that.
