### ISSUE TITLE
OAuth 2.0 files generated in the wrong directory

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#50]
I tried creating a new React Native app with this module today and noticed the OAuth 2.0-related files are created in a `src` directory rather than in my JHipster app's directory.

If I run `tree .` in the `src` directory, you can see the files:

```
➜  src git:(master) ✗ tree .
.
└── main
    └── java
        └── com
            └── okta
                └── developer
                    ├── config
                    │   └── ResourceServerConfiguration.java
                    └── web
                        └── rest
                            └── AuthInfoResource.java
```

The parent directory has:

```
react-native-app
jhipster-api
src
```

**Comment by ruddell** [comment]
I couldn't reproduce this, though it clearly happened to you.  Maybe with more details.  I added a test for this in https://github.com/ruddell/ignite-jhipster/commit/ba6eed3eff0c522d215603c204c1f0d804bf34ba and it works as expected

**Comment by mraible** [comment]
I'm working around this initial issue by manually moving the files into my `jhipster-api` project. I noticed that the following is printed to the console:

```
To configure OAuth2 OIDC Login, see docs/oauth2-oidc.md
```

I believe this should be a URL to the site since there is no "docs" folder created.

```
To configure OAuth2 OIDC Login, see https://github.com/ruddell/ignite-jhipster/blob/master/docs/oauth2-oidc.md
```

I followed the instructions that are listed on this page and nothing happens when I click the "Login" link in the sidebar.

![jhipster ignite login](https://user-images.githubusercontent.com/17892/46364325-bad53700-c632-11e8-9afe-5a173775790e.gif)

Out of curiosity, are you using a library to handle OIDC Login or do you have custom code that handles the callback and such?

**Comment by mraible** [comment]
I made it a little further! I had to modify my JHipster app's `SecurityConfiguration.java` to allow access to `/api/auth-info`. This makes it so the Login pops a browser and redirects to Keycloak.

```java
@Override
public void configure(HttpSecurity http) throws Exception {
    http
        .csrf()
        .csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
    .and()
        .addFilterBefore(corsFilter, CsrfFilter.class)
        .exceptionHandling()
        .authenticationEntryPoint(problemSupport)
        .accessDeniedHandler(problemSupport)
    .and()
        .logout()
        .logoutUrl("/api/logout")
        .logoutSuccessHandler(ajaxLogoutSuccessHandler())
        .permitAll()
    .and()
        .headers()
        .frameOptions()
        .disable()
    .and()
        .authorizeRequests()
        .antMatchers("/api/auth-info").permitAll()
        .antMatchers("/api/**").authenticated()
        .antMatchers("/management/health").permitAll()
        .antMatchers("/management/info").permitAll()
        .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN);

}
```

I also had to add `healthpoints://authorize` as a redirect URI to Keycloak. I modified the URL Types in Xcode, so I thought it'd use `oidc-example://authorize` instead.

![image](https://user-images.githubusercontent.com/17892/46365774-b874dc00-c636-11e8-8f1b-7ecd7d0372b7.png)

Now I get an error when it tries to redirect back to my app.

![image](https://user-images.githubusercontent.com/17892/46365827-d0e4f680-c636-11e8-9ef9-1c21b8a18cfb.png)

**Comment by ruddell** [comment]
When testing last night, I was able to authenticate successfully, but fetching entities threw an error saying something about a session/thread request.  I'm busy for the next few hours but will get back to you this afternoon/evening.  I haven't tested OAuth2 in a while so something may have changed in a React Native upgrade.

Right now the app uses a simple library for handling OIDC with some custom code. There's a better library but it requires a lot of changes to native code/dependencies (https://github.com/FormidableLabs/react-native-app-aut).  I'm trying to figure out a simple way to make those native changes without having to rewrite it every time React Native upgrades (same problem for the navigation library I want to use).

**Comment by mraible** [comment]
I was able to get OIDC auth working by changing the URL Types in my Xcode project to match the `appUrlScheme` in `App/Config/AppConfig.js`. So the main two issues seem to be:

1. Files are getting generated in the wrong directory. Do you expect users to generate the app _inside_ the same directory as their existing JHipster app? I'm doing it in a directory up from my JHipster app.
2. Security configuration doesn't get updated to allow `/api/auth-info`. 

I'd be happy to help this these issues. Is there a contributor guide? How do I make changes and then test them locally?

**Comment by ruddell** [comment]
The issue occurs when `jhipsterDirectory` is parsed from the prompts instead of passing it via `--jh-dir=`.  That part needs to be changed, which will fix both of the issues you mentioned.

See https://github.com/ruddell/ignite-jhipster/blob/master/contributing.md for how to use this project locally.

Note that when generating, you don't actually install `ignite-jhipster`. When you run `ignite new`, it downloads the latest tagged version from NPM and executes that.  So in dev, you just point to the directory it's cloned in.
