### ISSUE TITLE
Entity generator does not create relationship dropdowns

### ISSUE THREAD

**Issue by mraible** [ruddell/ignite-jhipster#57]
I created a new entity called `Points` with the following JDL:

```
entity BloodPressure {
  timestamp ZonedDateTime required,
  systolic Integer required,
  diastolic Integer required
}
entity Weight {
  timestamp ZonedDateTime required,
  weight Double required
}
entity Points {
  date LocalDate required,
  exercise Integer,
  meals Integer,
  alcohol Integer,
  notes String maxlength(140)
}
entity Preferences {
  weeklyGoal Integer required min(10) max(21),
  weightUnits Units required
}

enum Units {
  KG,
  LB
}

relationship OneToOne {
  Preferences{user(login)} to User
}
relationship ManyToOne {
  BloodPressure{user(login)} to User,
  Weight{user(login)} to User,
  Points{user(login)} to User
}

paginate BloodPressure, Weight with infinite-scroll
paginate Points with pagination
```

In my JHipster app, there's a User drop-down on the add/edit screen.

<img width="1186" alt="screen shot 2018-10-04 at 3 09 51 pm" src="https://user-images.githubusercontent.com/17892/46497257-0ed54c80-c7e8-11e8-9674-b815fbe2fce5.png">

In my React Native app, there is no drop-down.

<img width="545" alt="screen shot 2018-10-04 at 3 26 05 pm" src="https://user-images.githubusercontent.com/17892/46497906-dc2c5380-c7e9-11e8-8faf-f334ff1eae1d.png">

**Comment by ruddell** [comment]
Some work tonight:
 - enums https://github.com/ruddell/ignite-jhipster/commit/7ebf03af9dff742dd7262e4d64eb3e760abf1b54
 - add User "entity" reducer/saga/tests (I generated these but they seem to work) https://github.com/ruddell/ignite-jhipster/commit/454589c4efbe5dfdd81d4d54b4f2a149c6be7cb7
 - initial relationship support https://github.com/ruddell/ignite-jhipster/commit/07e4125391f7f9bb880d74dd8271af144b82d9e5

I tested your JDL and all of your entities now work as expected.  I also added a mapper method for the entity to/from the form value.  This lets you use those `boolean` Switches for the Points entity.

Remaining issues:
 - [ ] Related entities aren't loaded until you visit the edit screen, so they wont appear at first.   
    - If you go back then click edit/create again, they will be listed
 - [ ] Handle DTOs
 - [ ] Don't generate code for non-owner side entities

**Comment by mraible** [comment]
Good stuff @ruddell! I tested it out this morning and found a couple of issues:

1. The `entityToFormValue()` and `formValueToEntity()` methods are missing the id, so editing an entity results in a new one being created.
2. Does the React Native UI allow deleting entities? I don't see that option.
3. It does solve the issue of using toggles for integers. However, when I change a toggle from false to true and click save, the screen shows the toggle changing back to false before it saves. The value is saved correctly, but it's a weird visual.

Here's the code I'm using:

```
  entityToFormValue = (value) => {
    if (!value) {
      return {}
    }
    return {
      id: value.id || null,
      date: value.date || null,
      exercise: value.exercise === 1 ? true : false,
      meals: value.meals === 1 ? true : false,
      alcohol: value.alcohol === 1 ? true : false,
      notes: value.notes || null,
      userId: (value.user && value.user.id) ? value.user.id : null
    }
  }
  formValueToEntity = (value) => {
    return {
      id: value.id || null,
      date: value.date || null,
      exercise: (value.exercise) ? 1 : 0,
      meals: (value.meals) ? 1 : 0,
      alcohol: (value.alcohol) ? 1 : 0,
      notes: value.notes || null,
      user: {
        id: value.userId || null
      }
    }
  }
```

![toggle weirdness](https://user-images.githubusercontent.com/17892/46548946-7c43b480-c89e-11e8-80ca-fe9ed8dd877e.gif)

**Comment by ruddell** [comment]
Thanks for the tips.  I'll try to finish this up this weekend.

1) Easy fix
2) I noticed that last night.  The reducer is there but no button to actually delete an entity.
3) I'm guessing the value is being reset to the original in `componentWillReceiveProps`, should be a simple fix

It looks like I also should add a `SafeAreaView` for iPhone X support.

**Comment by ruddell** [comment]
Ya the relationship dropdown is mostly working, I added the remaining issues to a list in https://github.com/ruddell/ignite-jhipster/issues/38
