### ISSUE TITLE
Upgrade RN to 0.57 (Windows + Haste Module Issue)

### ISSUE THREAD

**Issue by sure1243jupiter** [ruddell/ignite-jhipster#61]
**Versions (please complete the following information):**
 - OS: windows 10
 - Ignite JHipster Version:  v1.12.2
 - Node Version: 8.11.3
- jhipsterVersion: 4.14.0,

**Describe the bug**
```
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! Invalid dependency type requested: alias

```
 generated new project from ignite-jhipster pointint to my jhipster server when i am installing node modules using "npm install" the packages are not installing and  getting this error in android in ios it is runnning

**Comment by ruddell** [comment]
Thanks for reporting, I usually use `yarn` so I missed this issue.  Just released v1.12.3 with the fix, you can also check the commit that closed this issue for the change, it's simple.

**Comment by sure1243jupiter** [comment]
please reopen it i have another issue after that

**Comment by ruddell** [comment]
Looks like it's [a React Native + Windows issue](https://github.com/facebook/react-native/issues/19953#issuecomment-407002494) and they decided not to backport the fix to v0.56 of React Native.  I guess we're forced to upgrade to v0.57+

I have limited time this week but I'll try to get it done sometime soon.  If you want it before then, you can fork/clone the boilerplate, revert this commit https://github.com/ruddell/ignite-jhipster/commit/dbfc86cae9c45276fd06066635b7d9359d6fca82, and run:

    ignite new MyAppName --boilerplate /full/path/to/cloned/boilerplate/folder

**Comment by sure1243jupiter** [comment]
thankyou @ruddell i will try

**Comment by sure1243jupiter** [comment]
**Environment:**
```
  OS: Windows 10
  Node: 8.11.3
  Yarn: 1.9.2
  npm: 6.3.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.1.0.0 AI-173.4819257
```

**Packages: (wanted => installed)**
```
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: 0.54.1 => 0.54.1
  ignite-jhipster: "^1.10.3",
  ignite-standard: "^1.0.0",
```

i have builded the ignite-jhipster project in these configurations and i can successfully build the project and ran it in android in windows environment...almost completing the project  now when i am building the same project in mac it is giving me error 

`/Users/xcodeclub/Library/Developer/Xcode/DerivedData/Lea*****y/Build/Intermediates.noindex/demo.build/Debug-iphonesimulator/demo.build/Script-00DD1BFF1BD5951E006B06BC.sh: line 3: ../node_modules/react-native/scripts/react-native-xcode.sh: No such file or directory`

I have also checked the build phases of my project in Xcode and there

```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

actually the file exists in the given path but when I am building the project it is giving error no such file or directory

could not able to find the exact issue....don't no may be it is issue between library versions or not
tried updating the latest react-native,ignite-jhipster versions and building but it did not worked for me.
please help me to solve my issue.

thanks @ruddell  in advance.

**Comment by ruddell** [comment]
That issue seems to be an issue with your react-native configuration, if you search Google there are many people with your problem so it's not specific to `ignite-jhipster`.  Sometimes `react-native` changes the paths between versions so if you just try to run `npm install` for a different version it won't work as expected.

I also just upgraded `react-native` to the latest version so your Windows issue should be fixed, I don't have a Windows computer to test on so I'm not positive.  New projects will use that version https://github.com/ruddell/ignite-jhipster/commit/c775c4de743f576eefb1d3327ac888991c3ba774
