### ISSUE TITLE
Entities saving on create and not update

### ISSUE THREAD

**Issue by balvinder294** [ruddell/ignite-jhipster#62]
Hey Ruddell, looks like a silly question, but I am able to create a new record in any entity, but when I try to update there is nothing happen after I click save. I was editing some date field as it was having an issue, so i tried another entity. The same issue is there the save works on new record and not on old record when we try to edit.
also, I have applied by setting some default value to fields, but I was unable to do that.
modified: {
            value: 'some_value',
            returnKeyType: 'done',
            onSubmitEditing: () => this.submitForm()
 }

My configuration
```
ignite --version 2.1.2
android emulator running Android 9

React dependencies in package.json
 "react": "16.4.1",
    "react-native": "0.56.1",

**Comment by ruddell** [comment]
Can you share the entity JDL or JSON files for one that is causing issues? Also what version of `ignite-jhipster` do you have in your `package.json`?   I'll have a better answer for you when I can test it out

**Comment by balvinder294** [comment]
Hi, i have     "ignite-jhipster": "1.12.3",
and entities i have issue on every, for edit only

like this questionLayer Entity
```
{
    "fluentMethods": true,
    "clientRootFolder": "",
    "relationships": [],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20181020132402",
    "dto": "mapstruct",
    "searchEngine": false,
    "service": "serviceImpl",
    "entityTableName": "question_layer",
    "jpaMetamodelFiltering": false,
    "pagination": "no"
}

```

**Comment by balvinder294** [comment]
Ohk ruddell thanks, can you give me any idea/hint for the issue, so I can also look into it also.

**Comment by ruddell** [comment]
I can't reproduce your editing issue, do you notice anything weird in the logs?  You can use Reactotron to see any API requests and Redux State changes.  Your `.yo-rc.json` from your `jhipster` app might help me reproduce (that's why there's an issue template).

To set a default value for new entities, set the `formValue` in `componentWillMount` (currently the code sets it to `{ }`.  I'm sure this could be improved.

**Comment by balvinder294** [comment]
Hi , the .yo-rc.json is here 
```
{
	"generator-jhipster": {
		"promptValues": {
			"packageName": "easygov",
			"nativeLanguage": "en"
		},
		"jhipsterVersion": "5.5.0",
		"applicationType": "gateway",
		"baseName": "easygov",
		"packageName": "easygov",
		"packageFolder": "easygov",
		"serverPort": "8082",
		"authenticationType": "uaa",
		"uaaBaseName": "account",
		"cacheProvider": "hazelcast",
		"enableHibernateCache": false,
		"websocket": false,
		"databaseType": "cassandra",
		"devDatabaseType": "cassandra",
		"prodDatabaseType": "cassandra",
		"searchEngine": false,
		"messageBroker": false,
		"serviceDiscoveryType": "consul",
		"buildTool": "maven",
		"enableSwaggerCodegen": true,
		"clientFramework": "angularX",
		"useSass": true,
		"clientPackageManager": "npm",
		"testFrameworks": [
			"gatling"
		],
		"jhiPrefix": "jhi",
		"enableTranslation": true,
		"nativeLanguage": "en",
		"languages": [
			"en",
			"hi"
		]
	}
}

```

and thanks for reactotron, i did not knew. That will help me if the issues is in Api call itself , again thanks for the solution

**Comment by balvinder294** [comment]
Finally made reactrotron to work, 
for new, when I click save there is a log, also the data is saving, with entity created message
![api response for save](https://user-images.githubusercontent.com/25227213/47630085-f3e6c580-db64-11e8-8247-6221509a41d1.png)

For update there is no log when i click on save, also no error or warning on mobile
![update api log question layer](https://user-images.githubusercontent.com/25227213/47630094-fc3f0080-db64-11e8-8f23-12c087ba4d2b.png)

I have other entities, that contains a localdate field, so i am trying with one entity questionLayer having two string fields only, it is default created with entity command. So does not why there is issue

**Comment by ruddell** [comment]
I still can't reproduce, even using a UAA, did you modify the entity's edit screen file at all?

**Comment by ruddell** [comment]
The `QUESTION_LAYER_REQUEST` is used for both update and create, the only difference is `put` vs `post` http method (and the lack of ID in a new entity).

I still can't reproduce the issue. :( I tried with the same backend (uaa gateway) with the QuestionLayer entity and I don't notice any issues.

**Comment by balvinder294** [comment]
No, I have not edited, entities they are default I am checking. Anyways, if the version change can help I will update and run again to see.

**Comment by ParasRocks** [comment]
Hey, I'm also facing the same issue. When i update the record nothing will happen.

**Comment by ruddell** [comment]
@ParasRocks As you can tell from my above messages, I can't reproduce the bug.  Do you have any more information that would help, such as specific steps that cause it to happen?  Does it only affect Android?

**Comment by balvinder294** [comment]
Hey @ruddell maybe the issue is only for Android i guess, can you test on that . We are using android only not ios.

**Comment by balvinder294** [comment]
Hey, @ruddell I tried again today by updating dependencies and ignite version, created a new app. The issue is same in updating, maybe the issue is with android only.

**Comment by balvinder294** [comment]
Hi @ruddell , the issue is with the setting value of object after submitting, in the update case.
The line here
```
const questionLayer = this.refs.form.getValue()
```
replacing with this 
```
const questionLayer = this.state.formValue
```

It looks like the t-comb-form native is having some issues or the value being referenced by  ref is not giving the values.
i have checked with the console, whenever we try to update, by the logic, the questionLayer object is always null, and as there is no case for handling the issue. The if case is skipped and there is no warning or alert.
```
 if (questionLayer) { // if validation fails, value will be null
      this.props.updateQuestionLayer(this.formValueToEntity(questionLayer))
    } 
```
maybe you can add like this, so people can know if there are null values going or just to check what is wrong with the method
```
 if (questionLayer) { // if validation fails, value will be null
      this.props.updateQuestionLayer(this.formValueToEntity(questionLayer))
    } else {  // one else case to handle failed update case and show alert
      Alert.alert('Error', 'Something went wrong updating the entity', [{text: 'OK'}])
    }
```

anyways thanks for maintaining the project, i will be sharing back to this project
