### ISSUE TITLE
Error building apk

### ISSUE THREAD

**Issue by sure1243jupiter** [ruddell/ignite-jhipster#68]
- OS: Windown10
 - Ignite JHipster Version:  react-native: "0.57.5", react-native-navigation: "2.1.3-snapshot.33"
 - Node Version: 8.12.0

When try to build the signed apk it is producing the errors but i am able to run it without any errors

` Task :react-native-navigation:compileReactNative51ReleaseJavaWithJavac FAILED
G:--\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\SyncUiImplementation.java:8: error: cannot find symbol
import com.facebook.react.uimanager.MeasureSpecProvider;
                                   ^
  symbol:   class MeasureSpecProvider
  location: package com.facebook.react.uimanager
G:---\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\SyncUiImplementation.java:9: error: cannot find symbol
import com.facebook.react.uimanager.SizeMonitoringFrameLayout;
                                   ^
  symbol:   class SizeMonitoringFrameLayout
  location: package com.facebook.react.uimanager
G:----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\SyncUiImplementation.java:78: error: cannot find symbol
    public <T extends SizeMonitoringFrameLayout & MeasureSpecProvider> void registerRootView(T rootView, int tag, ThemedReactContext context) {
                      ^
  symbol:   class SizeMonitoringFrameLayout
  location: class SyncUiImplementation
G:----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\SyncUiImplementation.java:78: error: cannot find symbol
    public <T extends SizeMonitoringFrameLayout & MeasureSpecProvider> void registerRootView(T rootView, int tag, ThemedReactContext context) {
                                                  ^
  symbol:   class MeasureSpecProvider
  location: class SyncUiImplementation
G:-----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\JsDevReloadHandlerFacade.java:7: error: JsDevReloadHandlerFacade is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class JsDevReloadHandlerFacade implements DevBundleDownloadListener, NavigationDevBundleDownloadListener {
       ^
G:----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\ReloadHandlerFacade.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
G:-----\node_modules\react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\react\ReloadHandler.java:3: error: ReloadHandler is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class ReloadHandler extends ReloadHandlerFacade implements JsDevReloadHandler.ReloadListener {
       ^
G:------\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\DevBundleDownloadListenerAdapter.java:7: error: DevBundleDownloadListenerAdapter is not abstract and does not override abstract method onSuccess(NativeDeltaClient) in DevBundleDownloadListener
public class DevBundleDownloadListenerAdapter implements DevBundleDownloadListener {
       ^
G:----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\DevBundleDownloadListenerAdapter.java:8: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: G:----\node_modules\react-native-navigation\lib\android\app\src\reactNative51\java\com\reactnativenavigation\react\SyncUiImplementation.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative51ReleaseJavaWithJavac'.
 Compilation failed; see the compiler error output for details.

 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 6m 39s
78 actionable tasks: 61 executed, 17 up-to-date`

**Comment by ruddell** [comment]
What command are you running to build for release (I think it changed with React Native Navigation)?  Try `cd android && ./gradlew app:assembleRelease`

I just tried [the workaround in their docs](https://github.com/wix/react-native-navigation/blob/v2/docs/docs/Installing.md#81-build-app-with-gradle-command) and it doesn't seem to work (I get this same issue), so I think a docs update showing the release process will be helpful.

**Comment by sure1243jupiter** [comment]
thanks @ruddell , 
the build is successful while using that command but it is not generating signed apk.
but when i build it using android studio(3.2 v) it is generating a signed apk and i am able to install it in my mobile device.

**Comment by ruddell** [comment]
Did you add your signing config into `android/app/build.gradle` like the [React Native docs](https://facebook.github.io/react-native/docs/signed-apk-android) say?  You have to add the `signingConfig` block, then reference it in the `buildTypes` `release` block.  Once doing both of those I get a signed `app-release.apk` in `android/app/build/outputs/apk/release/`

**Comment by sure1243jupiter** [comment]
oh, there been a small mistake i have forgotten to add line in` buildTypes` block.
now it is generating signed apk.
thankyou @ruddell

**Comment by ruddell** [comment]
Issue was solved, see #83 for tracking docs updates
