### ISSUE TITLE
Generate with websocket

### ISSUE THREAD

**Issue by neik279** [ruddell/ignite-jhipster#69]
Generate with backend supported websocket is not completed. Can you finish it, Ruddell?

**Comment by delkant** [comment]
I am having some issues with websockets too. Is there a way to disable websocket temporarily 'til the issue is fixed? Thanks!

```
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `../websockets/websocket-service` from `/Users/me/testapp/app/shared/reducers/create-store.js`: The module `../websockets/websocket-service` could not be found from `/Users/me/testapp/app/shared/reducers/create-store.js`. Indeed, none of these files exist:
  * `/Users/me/testapp/app/shared/websockets/websocket-service(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/me/testapp/app/shared/websockets/websocket-service/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)` (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.213
    RCTCxxBridge.mm:414
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

```

**Comment by delkant** [comment]
I found the issue:

It looks like some files have been renamed so there is a problem with the imports:

I've changed:

line 3 in websocket.sagas.js
replace
`import ChatActions from '../../modules/chat/chat.redux'`
with
`import ChatActions from '../../modules/chat/chat.reducer'`

line 5 in login.sagas.js
replace
`import WebsocketService from '../../shared/websockets/websocket-service'`
with
`import WebsocketService from '../../shared/websockets/websocket.service'`

after these changes the app is loading now(I haven't test yet if websockets are working properly ).

**Comment by ruddell** [comment]
@delkant Thanks for the hints, I needed to fix the imports and add the ChatScreen to `layouts.js`. I also added an end-to-end test to make sure the websockets and ChatScreen generate and work as expected.  

You can see the imports and changes to layout.js required [in this commit](https://github.com/ruddell/ignite-jhipster/pull/80/commits/14979cbbe394bac65af03271429c7c80551dc74f) and at the top of [this second one](https://github.com/ruddell/ignite-jhipster/pull/80/commits/b7863b9e83ab9049e69029d1ffd5ea3f5b65da64).  This is now released in the latest version.
