### ISSUE TITLE
couldn't run new app on Android, Windows 10

### ISSUE THREAD

**Issue by MustafaAkgure** [ruddell/ignite-jhipster#75]
1: Task failed with an exception.
Where:
Script 'C:\Users\inan\projects\IgniteJHipsterSampleApp\node_modules\react-native-navigation\lib\android\prepare-robolectric.gradle' line: 6

What went wrong:
A problem occurred evaluating script.

Could not find method testImplementation() for arguments [org.khronos:opengl-api:gl1.1-android-2.1_r1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

2: Task failed with an exception.
What went wrong:
A problem occurred configuring project ':react-native-navigation'.
compileSdkVersion is not specified.

I have used react-native 0.59, can you help me ?

**Comment by MustafaAkgure** [comment]
1: Task failed with an exception.
-----------
* Where:
Script 'C:\Users\inan\projects\IgniteJHipsterSampleApp\node_modules\react-native-navigation\lib\android\prepare-robolectric.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> Could not find method testImplementation() for arguments [org.khronos:opengl-api:gl1.1-android-2.1_r1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.


2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-navigation'.
> compileSdkVersion is not specified.

**Comment by ruddell** [comment]
I searched the React Native Navigation repository for that stack trace and it looks like it's due to some outdated Android libraries.  Tthe recommended solution is to "Open the project with android studio and accept every update we ask for."  Can you try that?

**Comment by MustafaAkgure** [comment]
Thanks for answering me! My all Android libraries is up to date. I install android sdk 28, 29 versions. I will install other versions of it.

**Comment by ruddell** [comment]
In Android Studio, if you open the project's `android` folder and run the gradle sync (`File` -> `Sync Project with Gradle Files`), it should notify you what libraries need to be installed/updated.  I was able to build and launch an Android app this morning on Mac, but I don't have a Windows computer to test with.

**Comment by ruddell** [comment]
Closing in favor of #83

**Comment by ruddell** [comment]
If you're still having issues, please open a new bug with the template filled out.  I can't debug this based on that stacktrace.

**Comment by MustafaAkgure** [comment]
Thanks ...
