### ISSUE TITLE
can't login using oauth2 - keycloak

### ISSUE THREAD

**Issue by Papua-coder** [ruddell/ignite-jhipster#76]
Hi Mr Ruddell,

I try to generate ignite project with jhipster properties : 
"applicationType": "gateway",
"authenticationType": "oauth2" - keycloak. 

jhipster version : 6.1.0

after that i try to run in android emulator. it return error user could not be found.
![image](https://user-images.githubusercontent.com/53078783/61522641-f663b500-aa3c-11e9-9d47-46990a692cb3.png)

i try to debug in jhipster code, there is different value that passing to spring boot
![image](https://user-images.githubusercontent.com/53078783/61522995-b2bd7b00-aa3d-11e9-83b3-ce0aa85ac7c7.png)

react native  : 
org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken@fb41a168: Principal: org.springframework.security.oauth2.jwt.Jwt@6eb9f288; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null; Granted Authorities: ROLE_USER, ROLE_ADMIN

jhipster front end : 
org.springframework.security.oauth2.client.authentication.OAuth2AuthenticationToken@2ca8e7a6: Principal: Name: [f46d7d00-84af-4331-aec9-b5901f01fdb4], Granted Authorities: [ROLE_USER], User Attributes: [sub=f46d7d00-84af-4331-aec9-b5901f01fdb4, email_verified=true, address={}, roles=[ROLE_USER, offline_access, ROLE_ADMIN, uma_authorization], iss=http://localhost:9080/auth/realms/jhipster, typ=ID, preferred_username=admin, given_name=Admin, aud=[web_app], acr=1, nbf=1970-01-01T00:00:00Z, azp=web_app, auth_time=1563519575, name=Admin Administrator, exp=2019-07-19T07:04:35Z, session_state=fd4c1679-522d-4893-b36a-8f6cb65d0849, family_name=Administrator, iat=2019-07-19T06:59:35Z, email=admin@localhost, jti=cdd0b238-057d-444d-bceb-993e034fb68c]; Credentials: [PROTECTED]; Authenticated: true; Details: null; Granted Authorities: ROLE_USER, ROLE_ADMIN

can you help me about this? 

Thanks

**Comment by ruddell** [comment]
I can reproduce, it looks like you need the changes from https://github.com/jhipster/generator-jhipster/pull/9905 in order to authenticate successfully.  These were included in v6.1.1+, you can either apply the changes from that PR or upgrade your backend to the latest JHipster

**Comment by Papua-coder** [comment]
Hi Mr Ruddell. Thanks for the info. i already try to upgrade to latest JHipster and the issue is fixed. 

Thanks
