### ISSUE TITLE
which fronted and backend framwork supprted by ignite

### ISSUE THREAD

**Issue by unknowedNp** [ruddell/ignite-jhipster#82]
sorry for my question , i cant find my answer by searching

I create jhipster app with angular front and kotlin/backend 
ignite support my app to create react native ?

or should i use generator-jhipster-ionic ?

**Comment by ruddell** [comment]
I have not tested with the Kotlin backend, if it uses the same API paths as a regular JHipster app then it should work fine.  Since `jhipster-kotlin` does not generate the frontend code, I think it does use the same API paths as expected.

The issue would be the same for generator-jhipster-ionic

**Comment by unknowedNp** [comment]
oh thanks
what about angular ? or vue ? is it supported ?

**Comment by ruddell** [comment]
The client you use for your webapp does not affect the backend API paths, so any frontend should work.  As of now, I have tested it with Angular/React.  

jhipster-vuejs [only generates frontend code](https://github.com/jhipster/jhipster-vuejs/tree/98a6a1336379e4768e9540ece6c9105a87493b11/generators) so I think it should be ok.

**Comment by unknowedNp** [comment]
thank a lot
