### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by ruddell** [ruddell/ignite-jhipster#83]
Need to document some features and differences from vanilla React Native apps.
 
- [x] Android Release build process requires `app:` prefix due to React Native Navigation - `cd android && ./gradlew app:assembleRelease` #68
- [x] Basic Fastlane implementation guide
- [x] Basic Detox implementation guide
- [x] Basic Storybook implementation guide
- [x] Update links to blog posts and videos
- [x] Document JDL requires only a single app to be present to do app generation #72

**Comment by MustafaAkgure** [comment]
Thanks ...
