### ISSUE TITLE
jhipster uaa + https backend - Bad credentials

### ISSUE THREAD

**Issue by orakso** [ruddell/ignite-jhipster#98]
**Describe the bug**

I have problem connecting Ignite to Jhipster Gateway (back-end) in prod mode with tls. 
I'm using  Jhipster UAA. UAA is in http mode and everything is working except Ignite. I can login directly form gateway, but if I try to login from Ignite, there is error Bad credentials. 
In dev mode, so that tls is turned off in gateway everything is working fine. The only change I made is apiUrl in app-config.js https://ip-address:8080/.

When I just comment tls section in backend:
server:
      port: 8080
//      ssl:
//         key-store: classpath:config/tls/keystore.p12
//         key-store-password: backend_keystore_passwd
//         key-store-type: PKCS12
//         key-alias: backend_keystore_alias
//         ciphers: ....
//         enabled-protocols: TLSv1.2

everything works fine.

What could be a problem?

**Instructions To reproduce**
Jhipster UAA in prod (without tls)
Jhipster Gateway in prod (with tls) - as Ignite backend
Jhipster Registry in prod (with tls)
Ignite Jhipster (dev, release)

**Comment by ruddell** [comment]
Are you accessing the gateway via a domain name that matches the cert?  Or using the IP like in your example `https://ip-address:8080/`?

I'll try to look into this issue over the weekend, busy until then.

**Comment by orakso** [comment]
> Are you accessing the gateway via a domain name that matches the TLS certificate? Or using the IP like in your example `https://ip-address:8080/`?
> 
> I'll try to look into this issue over the weekend, busy until then.

TLS certificate for backend (Jhipster gateway) is generated for ip-address. When I access gateway in browser by going to https://ip-address:8080 website everything works.

**Comment by ruddell** [comment]
How can I obtain an SSL certificate for an IP so that I can attempt to reproduce this? If you are using a self-signed certificate, then iOS and Android won't be able to validate it.

Does the login request reach the Gateway or UAA apps? Or is it an issue with TLS?

**Comment by orakso** [comment]
Login request does not reach gateway from Ignite.

**Comment by ruddell** [comment]
If you want to use self-signed certificates on an emulator or device, you will have to import and trust them on that emulator or device.

For iOS, [here's a video](https://www.loom.com/share/05009fd48472483b84334eac0c934164) showing that once the cert is imported and trusted by the device, it works as expected. For Android, it seems more complicated and I don't have the time now to look into it.

As this isn't an issue with the boilerplate itself, I'm closing the issue.  Feel free to keep commenting, especially if you figure it out.
